### ISSUE TITLE
List of URL Items

### ISSUE THREAD

**Issue by cpdunphy** [stleamist/BetterSafariView#1]
I've been running into trouble when trying to create a list of items that can be tapped to redirect to the SafariView.

I've tried to use the NaiveSafariView as shown in the demo doesn't give the behavior that I'd like (squished under the navigation view and tab bar)

The `.safariView` modifier is great, but not scaleable to a list of items. 

Attempts to resolve:

1. One work around would be to create a bunch of `$isPresented` State variables and assign each item to one of them, but it is not efficient or scaleable. 

2. Another work around is to just assign all of them to the same `$isPresented` State variable, but this poses a different problem which is that the Url of the webpage must be declared in advance and passed as context to the `.safariView` modifier, resulting in all items to return the same webpage. In this scenario the swipe to dismiss also causes a bug where it dismisses, goes back to the webpage, then dismisses again.

3. The last work around tried was to assign each row in the List its own State variable and bind the `.safariView` to that. But when clicked on that it sends the view into an infinite loop of popping and pushing the webpage that can only be stopped by pressing the "Done" button in the top left corner.

The only solution found currently is to use a navigation link to push a DetailView where the user is able to click "go to webpage" which then pushes to the webpage. This is not preferred as being able to go to the webpage from the original list of items is optimal.

Any ideas are appreciated.

**Comment by stleamist** [comment]
Hi Collin,

Thank you for creating the first issue on this repository. 😃

Using `.safariView(item:content:)` modifier released with [v2.0.0 update](/stleamist/BetterSafariView/releases/tag/v2.0.0) today, you can now present a Safari view with multiple URLs easily.

Here’s an example:

```swift
import SwiftUI
import BetterSafariView

struct ContentView: View {
    
    @State private var selectedURL: URL? = nil
    
    var body: some View {
        List {
            Button("Apple") {
                self.selectedURL = URL(string: "https://www.apple.com/")
            }
            Button("GitHub") {
                self.selectedURL = URL(string: "https://github.com/")
            }
        }
        .safariView(item: $selectedURL) { selectedURL in
            SafariView(url: selectedURL)
        }
    }
}
```

For more details, it would be helpful for you to have a look at [the demo project](/stleamist/BetterSafariView#demo). The issue where the Safari view is dismissed and presented again is also resolved on v2.0.0.

**Comment by cpdunphy** [comment]
Great!! Thanks to your instructions and the example in the demo project, I was able to get the list to behave as expected. (Also appreciate the easier configuration of the `SafariView`😁)

**Comment by gurugeek** [comment]
Hello and thank you for your package :)
My problem is that inside a list of articles if I use the current README example I get 2 instances/URLs  (belonging to 2 different articles) opens every time I click a button.


I now tried:
```

List(fetch.Novitadss) { Novitads in
                    VStack(alignment: .leading) {


 Button(action: {
                                self.selectedURL = URL(string: Novitads.link)
                                                               }) {
                                                                   Text(Novitads.title)
                                                                       .platformFontNegative()
                                                                           .italic()
                                                               }
                                                 
                            .safariView(item: $selectedURL) {selectedURL in
                                
                                
                                        SafariView(url: selectedURL)
                                    }
                            

```
but I get again 2 browsers opens at every click (just with the same link now).  Thanks in advance for your help.
