### ISSUE TITLE
No such module 'BetterSafariView'

### ISSUE THREAD

**Issue by RealTechyGod** [stleamist/BetterSafariView#5]
BetterSafariView has really messed up my project... can build but cant use editor and so many red errors.

Could not find module 'BetterSafariView' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64

**Comment by stleamist** [comment]
Hi @RealTechyGod,

That's an Xcode 12 bug from  **beta 6**(12A8189n) to **GM Seed 1**(12A208), which only occurs in the apps using `AuthenticationServices` with SwiftUI. ([68252534](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes#Overview))

Download **Xcode 12 GM Seed 2**(12A209) from the [App Store](https://apps.apple.com/app/xcode/id497799835), then it will be fixed.

I would appreciate it if you keep me updated on this issue. 😃
